apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-usuarios
  template:
    metadata:
      labels:
        app: msvc-usuarios
    spec:
      serviceAccountName: microservice-sa
      containers:
      - image: us-central1-docker.pkg.dev/project-gke-453903/usuarios/usuarios:latest
        name: usuarios
        ports:
        - containerPort: 8001
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: msvc-usuarios
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: msvc-usuarios
                key: db_host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: msvc-usuarios
                key: database
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: msvc-usuarios
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msvc-usuarios
                key: password
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "350m"

