apiVersion: v1
kind: Service
metadata:
  name: msvc-usuarios-service
  namespace: dev
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  selector:
    app: msvc-usuarios
  type: LoadBalancer